---
title: "Everyday LA meeting (Flexboard)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(gsheet)
suppressMessages(library(dplyr))

URL <- 'https://docs.google.com/spreadsheets/d/14NTHdvt5lEv-sbSpUli6gCx9TOmf8bOCLbFsb6ezNSA/edit?usp=sharing'

# Define the data gathering function here? possibly using
# http://shiny.rstudio.com/reference/shiny/latest/reactivePoll.html
# http://shiny.rstudio.com/gallery/reactive-poll-and-file-reader.html
pollData <- reactivePoll(5000, session,
                     readTimestamp <- function(){
                        # We read the latest response timestamp
                        data <- as.data.frame(gsheet2tbl(URL))
                        if(nrow(data)>0 && ncol(data)>1){
                          data[nrow(data),1]
                        }else{
                          ""
                        }
                      },
                     readValue <- function(){
                        data <- as.data.frame(gsheet2tbl(URL))
                        #We clean it up a bit
                        names(data) <- c("Timestamp","Homework")
                        data$Homework <- as.factor(data$Homework)
                        data
                      })

getFactorNumber <- function(data, value){
  n <- as.integer(table(data$Homework)[value])
  n
}
```


Row
-----------------------------------------------------------------------

### Read the Doc

```{r}


reads <- reactive(getFactorNumber(pollData(), 'Yes, fully'))
renderValueBox({
              read <- reads()
               valueBox(
                 value = read,
                 icon = "fa-smile-o",
                 color="success")
                })
```

### Skimmed the Doc

```{r}
skims <- reactive(getFactorNumber(pollData(), 'I skimmed through it quickly'))
renderValueBox({
              skim <- skims()
              valueBox(
                value=skim,
                icon = "fa-flash",
                color="warning")
                })
```

### Didn't do it!

```{r}
nowork <- reactive(getFactorNumber(pollData(), 'No'))
renderValueBox({
              now <- nowork()
              valueBox(
                value = now,
                 icon = "fa-frown-o",
                 color = "danger")
              })
```

Row
-----------------------------------------------------------------------

```{r}
renderTable(pollData())
```